language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-27.0.2
    - android-26
    - extra-android-m2repository
    - extra-android-support
  licenses:
      - android-sdk-license-.+
      - '.+'

before_install:
  - chmod +x gradlew
  yes | sdkmanager --licenses
  mkdir -p "$ANDROID_SDK/licenses"
  echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
  echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"

script:
  - ./gradlew assembleRelease